import test from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { ProductStore, Conflict } from "../src/store/postgres.js";
import { CoreService } from "../src/core/service.js";
import { HindsightEngine } from "../src/adapters/hindsight/engine.js";
const url=process.env.LESSONLOOP_TEST_DATABASE_URL;
if(!url)throw new Error("LESSONLOOP_TEST_DATABASE_URL is required for actual PostgreSQL tests");
test("PostgreSQL migration, singleton, durable idempotency, CAS and source-role binding",async()=>{
  let store=new ProductStore(url); await store.open(true);
  const contender=new ProductStore(url); await assert.rejects(contender.open(),/another_core/); await contender.close();
  const scope=randomUUID(); const p={id:"owner",channel:"user" as const,scopes:[scope]};
  const engine=new HindsightEngine("http://127.0.0.1:19888","integration-unused");
  let core=new CoreService(store,engine);
  await core.configure(p,{scopeId:scope,expectedRevision:0,learning:true,recommendation:false,review:false,notifications:false});
  await assert.rejects(core.configure(p,{scopeId:scope,expectedRevision:0,learning:false,recommendation:false,review:false,notifications:false}),Conflict);
  const agent={...p,id:`agent-${scope}`,channel:"agent" as const};
  const material={scopeId:scope,segments:[{text:"A real input retained for the store integration test.",role:"tool"}]};
  const accepted=await core.submitMaterial(agent,material,"event-1");
  assert.equal(accepted.accepted,true);
  const stored=await core.inspect(agent,"material",accepted.materialId) as unknown as {segments:Array<{role:string}>};
  assert.equal(stored.segments[0]!.role,"agent");
  await assert.rejects(core.submitMaterial(agent,{...material,segments:[{text:"changed",role:"tool"}]},"event-1"),/idempotency_conflict/);
  await store.close();store=new ProductStore(url);await store.open();core=new CoreService(store,engine);
  const duplicate=await core.submitMaterial(agent,material,"event-1");assert.equal(duplicate.duplicate,true);assert.equal(duplicate.jobId,accepted.jobId);
  await core.cancelJob(agent,accepted.jobId);assert.equal((await core.getJob(agent,accepted.jobId)).status,"canceled");
  await assert.rejects(core.inspect({...p,scopes:[]},"material",accepted.materialId),/not_found/);
  const task=await core.startTask(p,scope);
  const obs={taskRef:task.taskRef,eventId:"obs",text:"Observed file type",values:{kind:"manual"},completedStepIds:[],conditionResults:{}};
  assert.equal((await core.observe(p,obs)).duplicate,false);assert.equal((await core.observe(p,obs)).duplicate,true);
  await assert.rejects(core.observe(agent,obs),/trusted_observation_required/);
  await store.close();
});
